### ISSUE TITLE
OpenTelemetryServerFilter causes failure for certain sub-resource definitions

### ISSUE THREAD

**Issue by jasondlee** [smallrye/smallrye-opentelemetry#224]
Take the following resource and sub-resource definition:

```
@Path("widgets")
public class WidgetsResource {
    @GET
    @Path("offers")
    public WidgetList getDiscounted() {...}

    @Path("{id}")
    public WidgetResource findWidget(@PathParam("id") String id) {
        return new WidgetResource(id);
    }
}

public class WidgetResource {
    public WidgetResource(String id) {...}

    @GET
    public Widget getDetails() {...}
}
```

With SR OpenTelemetry integrated in WildFly, we're seeing failures like this:

```
RESTEASY002375: Error processing request GET /subresource/api/person/Jozef - org.jboss.as.test.integration.jaxrs.subresource.PersonResource.getName: java.lang.IllegalArgumentException: RESTEASY003135: Class must be annotated with @Path to invoke path(Class)
  at org.jboss.resteasy.resteasy-core@6.2.3.Final//org.jboss.resteasy.specimpl.ResteasyUriBuilderImpl.path(ResteasyUriBuilderImpl.java:400)
  at jakarta.ws.rs.api@3.1.0//jakarta.ws.rs.core.UriBuilder.fromResource(UriBuilder.java:129)
  at io.smallrye.opentelemetry@2.3.0//io.smallrye.opentelemetry.implementation.rest.OpenTelemetryServerFilter$HttpServerAttributesExtractor.route(OpenTelemetryServerFilter.java:172)
  at io.smallrye.opentelemetry@2.3.0//io.smallrye.opentelemetry.implementation.rest.OpenTelemetryServerFilter$HttpServerAttributesExtractor.route(OpenTelemetryServerFilter.java:149)
```

The problem comes from requests to `/widgets/{id}` which resolves to `WidgetResource.getDetails()`. For that class, though, there is no `@Path` annotation, so calls to `UriBuilder.fromResource()` fail. Likewise, calls to `UriBuilder.fromMethod()` will not work either, due to `getDetails()` not having the annotation either.

Based on the javadocs for `HTTP_ROUTE`, it seems the correct thing to do in this scenario is to simply return null for value, but we're open to other suggestions. :)

The WildFly test failing can be found here: https://github.com/jasondlee/wildfly/blob/main/testsuite/integration/basic/src/test/java/org/jboss/as/test/integration/jaxrs/subresource/SubResourceTestCase.java

**Comment by marcosgopen** [comment]
We encountered also this issue. In our case we have also the following warning:
`WARN  [org.jboss.resteasy.resteasy_jaxrs.i18n] (ServerService Thread Pool -- 25) RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.wildfly.extension.opentelemetry.api.OpenTelemetryClientRequestFilter from jar:file:/home/msappegr/Downloads/wildfly/dist/target/wildfly-28.0.0.Beta1-SNAPSHOT/modules/system/layers/base/org/wildfly/extension/opentelemetry-api/main/wildfly-opentelemetry-api-28.0.0.Beta1-SNAPSHOT.jar!/META-INF/services/jakarta.ws.rs.ext.Providers: java.lang.ClassNotFoundException: org.wildfly.extension.opentelemetry.api.OpenTelemetryClientRequestFilter from [Module "deployment.OpenAPIIT.war" from Service Module Loader]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:200)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	at org.jboss.resteasy.resteasy-core@6.2.3.Final//org.jboss.resteasy.plugins.providers.RegisterBuiltin.registerProviders(RegisterBuiltin.java:95)
	at org.jboss.resteasy.resteasy-core@6.2.3.Final//org.jboss.resteasy.plugins.providers.RegisterBuiltin.register(RegisterBuiltin.java:74)
	at org.jboss.resteasy.resteasy-core@6.2.3.Final//org.jboss.resteasy.core.ResteasyDeploymentImpl.startInternal(ResteasyDeploymentImpl.java:154)
	at org.jboss.resteasy.resteasy-core@6.2.3.Final//org.jboss.resteasy.core.ResteasyDeploymentImpl.start(ResteasyDeploymentImpl.java:127)
	at org.jboss.resteasy.resteasy-core@6.2.3.Final//org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:144)
	at org.jboss.resteasy.resteasy-core@6.2.3.Final//org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:42)
	at io.undertow.servlet@2.3.4.Final//io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
	at org.wildfly.security.elytron-web.undertow-server-servlet@3.0.0.Final//org.wildfly.elytron.web.undertow.server.servlet.RunAsLifecycleInterceptor.doIt(RunAsLifecycleInterceptor.java:70)
	at org.wildfly.security.elytron-web.undertow-server-servlet@3.0.0.Final//org.wildfly.elytron.web.undertow.server.servlet.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:76)
	at io.undertow.servlet@2.3.4.Final//io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
	at io.undertow.servlet@2.3.4.Final//io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:304)
	at io.undertow.servlet@2.3.4.Final//io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:140)
	at io.undertow.servlet@2.3.4.Final//io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:588)
	at io.undertow.servlet@2.3.4.Final//io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:559)
	at io.undertow.servlet@2.3.4.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet@2.3.4.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow@28.0.0.Beta1-SNAPSHOT//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1430)
	at org.wildfly.extension.undertow@28.0.0.Beta1-SNAPSHOT//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1430)
	at org.wildfly.extension.undertow@28.0.0.Beta1-SNAPSHOT//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1430)
	at org.wildfly.extension.undertow@28.0.0.Beta1-SNAPSHOT//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1430)
	at io.undertow.servlet@2.3.4.Final//io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:601)
	at org.wildfly.extension.undertow@28.0.0.Beta1-SNAPSHOT//org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:106)
	at org.wildfly.extension.undertow@28.0.0.Beta1-SNAPSHOT//org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:87)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)
`
